# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 15:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='samplemap',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_th', models.CharField(max_length=254)),
                ('name_en', models.CharField(max_length=254)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=2180)),
            ],
        ),
    ]
